language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - pip install pyflakes
before_script:
  - git config --global user.email "foo@example.com"
  - git config --global user.name "foo"
script:
  - python setup.py make_versioneer
  - python test/test_git.py
  - pyflakes setup.py versioneer.py
