os: linux
arch: amd64
dist: bionic
language: python
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

branches:
  except:
    - /^WIP-.*$/

python:
  - 3.6
  - 3.7
  - 3.8
  - pypy
  - pypy3

install:
  - pip install "tox<3.0.0" tox-travis

script:
  - tox

jobs:
  allow_failures:
    - python: pypy3
